#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Mediando.Droid.Resource", IsApplication=true)]

namespace Mediando.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::Mediando.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::Mediando.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int C26 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int corning = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Corning1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int CorningLibrary = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int DocumentsFolder32 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int emea_button = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int GlobeFilled32 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Home32 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Library32 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int NewsFilled32 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int next = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int pdfthumb = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int RightRound26 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int RightRound32 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Settings32 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int tap = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ViewDetailsFilled32 = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
