// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MediandoUI {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MediandoUI.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string NoResultsText {
            get {
                return ResourceManager.GetString("NoResultsText", resourceCulture);
            }
        }
        
        internal static string CorningLibraryImagePhone {
            get {
                return ResourceManager.GetString("CorningLibraryImagePhone", resourceCulture);
            }
        }
        
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        internal static string CorningLibraryImagePad {
            get {
                return ResourceManager.GetString("CorningLibraryImagePad", resourceCulture);
            }
        }
        
        internal static string ReadOnlineText {
            get {
                return ResourceManager.GetString("ReadOnlineText", resourceCulture);
            }
        }
        
        internal static string MyDocsIcon {
            get {
                return ResourceManager.GetString("MyDocsIcon", resourceCulture);
            }
        }
        
        internal static string LibraryIcon {
            get {
                return ResourceManager.GetString("LibraryIcon", resourceCulture);
            }
        }
        
        internal static string DownloadText {
            get {
                return ResourceManager.GetString("DownloadText", resourceCulture);
            }
        }
        
        internal static string NewsLetterIcon {
            get {
                return ResourceManager.GetString("NewsLetterIcon", resourceCulture);
            }
        }
        
        internal static string TempFilesDeletedMessage {
            get {
                return ResourceManager.GetString("TempFilesDeletedMessage", resourceCulture);
            }
        }
        
        internal static string DownloadVideoMessage {
            get {
                return ResourceManager.GetString("DownloadVideoMessage", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string DownloadviaWifi {
            get {
                return ResourceManager.GetString("DownloadviaWifi", resourceCulture);
            }
        }
        
        internal static string DeleteMediaFiles {
            get {
                return ResourceManager.GetString("DeleteMediaFiles", resourceCulture);
            }
        }
        
        internal static string NewsLetterLinkDescription {
            get {
                return ResourceManager.GetString("NewsLetterLinkDescription", resourceCulture);
            }
        }
        
        internal static string DeleteMediaMessage {
            get {
                return ResourceManager.GetString("DeleteMediaMessage", resourceCulture);
            }
        }
        
        internal static string AboutCorning {
            get {
                return ResourceManager.GetString("AboutCorning", resourceCulture);
            }
        }
        
        internal static string MediaFilesDeletedMessage {
            get {
                return ResourceManager.GetString("MediaFilesDeletedMessage", resourceCulture);
            }
        }
        
        internal static string PlayOnlineText {
            get {
                return ResourceManager.GetString("PlayOnlineText", resourceCulture);
            }
        }
        
        internal static string ProductCatalogLink {
            get {
                return ResourceManager.GetString("ProductCatalogLink", resourceCulture);
            }
        }
        
        internal static string SettingsIcon {
            get {
                return ResourceManager.GetString("SettingsIcon", resourceCulture);
            }
        }
        
        internal static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        internal static string DeleteDocumentMessage {
            get {
                return ResourceManager.GetString("DeleteDocumentMessage", resourceCulture);
            }
        }
        
        internal static string ProductCatalog {
            get {
                return ResourceManager.GetString("ProductCatalog", resourceCulture);
            }
        }
        
        internal static string StartIcon {
            get {
                return ResourceManager.GetString("StartIcon", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string DeleteTempFiles {
            get {
                return ResourceManager.GetString("DeleteTempFiles", resourceCulture);
            }
        }
        
        internal static string CategoriesTitle {
            get {
                return ResourceManager.GetString("CategoriesTitle", resourceCulture);
            }
        }
        
        internal static string AboutCorningLinkMainText {
            get {
                return ResourceManager.GetString("AboutCorningLinkMainText", resourceCulture);
            }
        }
        
        internal static string NewsLetterLinkMainText {
            get {
                return ResourceManager.GetString("NewsLetterLinkMainText", resourceCulture);
            }
        }
        
        internal static string PlayOfflineText {
            get {
                return ResourceManager.GetString("PlayOfflineText", resourceCulture);
            }
        }
        
        internal static string AppTitleText {
            get {
                return ResourceManager.GetString("AppTitleText", resourceCulture);
            }
        }
        
        internal static string LanguagesTitle {
            get {
                return ResourceManager.GetString("LanguagesTitle", resourceCulture);
            }
        }
        
        internal static string DoneLabel {
            get {
                return ResourceManager.GetString("DoneLabel", resourceCulture);
            }
        }
        
        internal static string MyDocsLinkDescription {
            get {
                return ResourceManager.GetString("MyDocsLinkDescription", resourceCulture);
            }
        }
        
        internal static string MyDocsLinkMainText {
            get {
                return ResourceManager.GetString("MyDocsLinkMainText", resourceCulture);
            }
        }
        
        internal static string DeleteVideoMessage {
            get {
                return ResourceManager.GetString("DeleteVideoMessage", resourceCulture);
            }
        }
        
        internal static string AboutCorningLinkDescription {
            get {
                return ResourceManager.GetString("AboutCorningLinkDescription", resourceCulture);
            }
        }
        
        internal static string HomeIcon {
            get {
                return ResourceManager.GetString("HomeIcon", resourceCulture);
            }
        }
        
        internal static string LibraryLinkDescription {
            get {
                return ResourceManager.GetString("LibraryLinkDescription", resourceCulture);
            }
        }
        
        internal static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        internal static string LibraryLinkMainText {
            get {
                return ResourceManager.GetString("LibraryLinkMainText", resourceCulture);
            }
        }
        
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        internal static string DownloadDocumentMessage {
            get {
                return ResourceManager.GetString("DownloadDocumentMessage", resourceCulture);
            }
        }
        
        internal static string CorningWebsite {
            get {
                return ResourceManager.GetString("CorningWebsite", resourceCulture);
            }
        }
        
        internal static string CorningWebsiteLink {
            get {
                return ResourceManager.GetString("CorningWebsiteLink", resourceCulture);
            }
        }
        
        internal static string ReadOfflineText {
            get {
                return ResourceManager.GetString("ReadOfflineText", resourceCulture);
            }
        }
    }
}
